import = [
    "~/.config/alacritty/themes/alabaster_dark.toml"
]

[font]
size = 12
[font.bold]
family = "BlexMono Nerd Font"
[font.bold_italic]
family = "BlexMono Nerd Font"
[font.italic]
family = "BlexMono Nerd Font"
[font.normal]
family = "BlexMono Nerd Font"

[window]
opacity = 1.00

[window.padding]
x = 5
y = 5

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "alt"
