import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
size = 11
[font.bold]
family = "Monospace"
[font.bold_italic]
family = "Monospace"
[font.italic]
family = "Monospace"
[font.normal]
family = "Monospace"

[window]
opacity = 1.00

[window.padding]
x = 12
y = 12

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "alt"
