import = [
#    "~/.config/alacritty/themes/alabaster_dark.toml"
]

[font]
size = 11
[font.bold]
family = "Monospace"
[font.bold_italic]
family = "Monospace"
[font.italic]
family = "Monospace"
[font.normal]
family = "Monospace"

[window]
opacity = 0.95

[window.padding]
x = 10
y = 10

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "alt"
