import = [
    "~/.config/alacritty/themes/everforest_dark.toml"
]

[font]
size = 11
[font.bold]
family = "JetBrains Mono Nerd Font"
[font.bold_italic]
family = "JetBrains Mono Nerd Font"
[font.italic]
family = "JetBrains Mono Nerd Font"
[font.normal]
family = "JetBrains Mono Nerd Font"

[window]
# opacity = 0.90

[window.padding]
x = 12
y = 12

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "alt"
